name: Docker Image CI

on:
  push:
    branches: [ vue3 ]
  pull_request:
    branches: [ vue3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    - name: Docker Repository Configuration
      uses: azure/docker-login@v1
      with:
        login-server: parstat.azurecr.io # default: index.docker.io
        username: parstat
        password:  ${{ secrets.REGISTRY_PASSWORD }} 
    - name: Docker Image build & push
      run: |
        docker build . --file Dockerfile --tag parstat.azurecr.io/iais-frontend:latest
        docker push parstat.azurecr.io/iais-frontend:latest
    - name: Push to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: cd iais && docker stack deploy --compose-file docker-compose.yml --with-registry-auth iais
