name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the app
      run: |
          npm install
          npm run build
    - name: Docker Repository Configuration
      uses: azure/docker-login@v1
      with:
        login-server: parstat.azurecr.io # default: index.docker.io
        username: parstat
        password:  ${{ secrets.REGISTRY_PASSWORD }} 
    - name: Docker Image build & push
      run: |
        docker build . --file Dockerfile --tag parstat.azurecr.io/iais-frontend:latest
        docker push parstat.azurecr.io/iais-frontend:latest
