name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Repository Configuration
      uses: azure/docker-login@v1
      env:
        REGISTER_PASSWORD: ${{ secrets.REGISTER_PASSWORD }} 
      with:
        login-server: parstat.azurecr.io # default: index.docker.io
        username: parstat
        password: $REGISTER_PASSWORD
    - name: Build the app
      run: |
          npm install
          npm run build
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag parstat.azurecr.io/iais-frontend:latest
        docker push parstat.azurecr.io/iais-frontend:latest
